# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 00:11
from __future__ import unicode_literals

from django.db import migrations
import tracks.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_content_file_image_text_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=tracks.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=tracks.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
